apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1-dep
  labels:
    app: app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: app-1
        image: hashicorp/http-echo
        args:
          - "-text=Hello World from [app-1-dep-$(hostname)]!"
        ports:
          - name: http
            containerPort: 80
