apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2-dep
  labels:
    app: app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
      - name: app-2
        image: hashicorp/http-echo
        args:
          - "-text=Hello World from [app-2-dep-$(hostname)]!"
        ports:
          - name: http
            containerPort: 80
